apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server
          image: melkeor/api-server
          ports:
            - containerPort: 3000
              name: nodejs-port
  selector:
    matchLabels:
      app: api-server