apiVersion: v1
kind: Service
metadata:
  name: api-server-service
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  type: LoadBalancer #NodePort
  selector:
    app: api-server