apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: melkeor/react-app
          ports:
            - containerPort: 8000
              name: http-port
  selector:
    matchLabels:
      app: react-app